session_name: dev
windows:
- window_name: code
  layout: tiled
  shell_command_before:
    - 'cd ~/shia/shia && source ~/shia/bin/activate'
  panes:
    - shell_command:
        - emacsclient -a "" -t "$@"
- window_name: polymer
  shell_command_before:
    - 'cd ~/shia/shia/frontend && source ~/shia/bin/activate'
  panes:
    - shell_command:
        - cd shia/
        - polymer serve
- window_name: django
  shell_command_before:
    - 'cd ~/shia/shia && source ~/shia/bin/activate'
  panes:
      - shell_command:
          - python manage.py runserver
